name: Google Indexing API Auto Submit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行

jobs:
  google-indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-auth requests lxml

      - name: Generate Google API Access Token
        id: get_token
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}' > service_account.json
          token=$(python - <<EOF
          import json
          from google.oauth2 import service_account
          from google.auth.transport.requests import Request
          
          SCOPES = ["https://www.googleapis.com/auth/indexing"]
          SERVICE_ACCOUNT_FILE = "service_account.json"
          
          credentials = service_account.Credentials.from_service_account_file(
              SERVICE_ACCOUNT_FILE, scopes=SCOPES
          )
          credentials.refresh(Request())
          print(credentials.token)
          EOF
          )
          echo "access_token=$token" >> $GITHUB_ENV

      - name: Fetch sitemap and extract URLs
        id: fetch_sitemap
        run: |
          SITE_URL="https://blog.chencs.online/sitemap.xml"
          echo "Fetching sitemap from $SITE_URL"
          
          urls=$(curl -s $SITE_URL | xmllint --xpath '//loc/text()' -)
          
          # 将 URLs 形式化为 JSON
          urls_json=$(echo "$urls" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          
          echo "URLs extracted: $urls_json"
          echo "urls=$urls_json" >> $GITHUB_ENV

      - name: Submit URLs to Google Indexing API
        run: |
          for url in $(echo $urls | jq -r '.[]'); do
            RESPONSE=$(curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $ACCESS_TOKEN" \
              -d "{\"url\": \"$url\", \"type\": \"URL_UPDATED\"}" \
              "https://indexing.googleapis.com/v3/urlNotifications:publish")
            echo "Submitted $url: $RESPONSE"
          done
