name: Google Indexing API Auto Submit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行

jobs:
  google-indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-auth requests

      - name: Generate Google API Access Token
        id: get_token
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}' > service_account.json
          token=$(python - <<EOF
          import json
          from google.oauth2 import service_account
          from google.auth.transport.requests import Request
          
          SCOPES = ["https://www.googleapis.com/auth/indexing"]
          SERVICE_ACCOUNT_FILE = "service_account.json"
          
          credentials = service_account.Credentials.from_service_account_file(
              SERVICE_ACCOUNT_FILE, scopes=SCOPES
          )
          credentials.refresh(Request())
          print(credentials.token)
          EOF
          )
          echo "access_token=$token" >> $GITHUB_OUTPUT

      - name: Submit URLs to Google Indexing API
        env:
          ACCESS_TOKEN: ${{ steps.get_token.outputs.access_token }}
        run: |
          URLS_TO_SUBMIT=(
            "https://blog.chencs.online/about/"
            "https://blog.chencs.online"
            "https://blog.chencs.online/posts/%E4%BA%8C%E5%88%86%E6%9F%A5%E6%89%BE%E6%80%BB%E7%BB%93%E4%B8%8E%E4%BE%8B%E9%A2%98/"
            "https://blog.chencs.online/categories/%E7%AE%97%E6%B3%95%E4%B8%8E%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/"
            "https://blog.chencs.online/posts/%E7%AE%97%E6%B3%95%E9%A2%98-%E7%B4%A2%E5%BC%95/"
            "https://blog.chencs.online/posts/"
            "https://blog.chencs.online/posts/%E7%8C%AB%E5%92%8C%E8%80%81%E9%BC%A0-lc/"
            "https://blog.chencs.online/posts/os-note/"
            "https://blog.chencs.online/posts/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%BA%94%E8%AF%95%E7%AC%94%E8%AE%B0/"
            "https://blog.chencs.online/posts/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E5%BA%94%E8%AF%95%E7%AC%94%E8%AE%B0/"
            "https://blog.chencs.online/posts/%E6%95%B0%E8%AE%BA%E5%9F%BA%E7%A1%80/"
            "https://blog.chencs.online/posts/%E8%B5%84%E6%BA%90%E5%88%86%E9%85%8D%E5%BC%8F%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92/"
            "https://blog.chencs.online/posts/house_price/"
          )
          for URL in "${URLS_TO_SUBMIT[@]}"; do
            RESPONSE=$(curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $ACCESS_TOKEN" \
              -d "{\"url\": \"$URL\", \"type\": \"URL_UPDATED\"}" \
              "https://indexing.googleapis.com/v3/urlNotifications:publish")
            echo "Submitted $URL: $RESPONSE"
          done
